FROM debian:trixie-slim

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y install --no-install-recommends \
    sudo \
    curl \
    wget \
    gnupg \
    ca-certificates \
    apt-transport-https \
    tar \
    just && \
    \
    wget -O /usr/local/bin/hadolint \
    https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 && \
    chmod +x /usr/local/bin/hadolint && \
    \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
